name: Tests

# * Controls
# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

# * Jobs
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-20.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Check shell files (shellcheck)
        run: |
          sudo apt-get update -y
          sudo apt-get install shellcheck
          cd src
          ./shellcheck.sh

      - name: Check dockerfile (hadolint)
        run: |
          cd src
          ./dockerfile_check.sh

  build:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Build images
        run: |
          cd ${GITHUB_WORKSPACE}/src
          set -a; source VERSION ; set +a;
          docker build \
          --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          --build-arg S6_OVERLAY_VERSION="${S6_OVERLAY_VERSION}" \
          --build-arg UBUNTU_VERSION="${UBUNTU_VERSION}" \
          -t oupfiz5/ubuntu-s6:${{ github.sha }} \
          -f ./Dockerfile \
          .
