name: Tests

# * Controls
# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]
#    paths:
#      - .github/workflows/*
#      - .github/*
#      - Dockerfile
#      - rootfs/*
#      - hook/*


# * Jobs
jobs:
  checks:
    name: Checks shell code and Dockerfile
    runs-on: ubuntu-20.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Check shell files (shellcheck)
        run: |
          sudo apt-get update -y
          sudo apt-get install shellcheck
          cd src
          ./shellcheck.sh

      - name: Check dockerfile (hadolint)
        run: |
          cd src
          ./dockerfile_check.sh

  build_docker_image:
    name: Build docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Repo checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          cd ${GITHUB_WORKSPACE}/src
          set -a; source VERSION ; set +a;
          docker build \
          --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
          --build-arg S6_OVERLAY_VERSION="${S6_OVERLAY_VERSION}" \
          --build-arg UBUNTU_VERSION="${UBUNTU_VERSION}" \
          -t "oupfiz5/ubuntu-s6:${{ github.sha }}" \
          -f ./Dockerfile \
          .

      - name: Check image (dockle)
        run: |
          cd ${GITHUB_WORKSPACE}/src
          docker image ls
          ./docker_image_check.sh "oupfiz5/ubuntu-s6:${{ github.sha }}"

      - name: Check container
        run: |
          cd ${GITHUB_WORKSPACE}/tests
          docker run -d --rm --name=ubuntu-s6 "oupfiz5/ubuntu-s6:${{ github.sha }}"
          sleep 5
          docker container inspect ubuntu-s6
          tests/.bats-battery/bats-core/bin/bats tests/
          docker container stop ubuntu-s6
